# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

task default: :spec

task :build_many do
  platforms = {
    'x86_64-linux'    => [ 'linux/amd64', 'linux-musl/amd64' ],
    'aarch64-linux'   => [ 'linux/arm64', 'linux-musl/arm64' ],
    'x86_64-darwin'   => [ 'macos/amd64'   ],
    'arm64-darwin'    => [ 'macos/arm64'   ],
    'x64-mingw32'     => [ 'windows/amd64' ],
    'aarch64-mingw32' => [ 'windows/arm64' ],
  }

  platforms.each do |platform, platform_dirs|
    puts "Building gem for #{platform}"

    gem_dir = "/tmp/#{platform}"
    FileUtils.mkdir(gem_dir, verbose: true)
    FileUtils.cp_r("#{FileUtils.pwd}/.", gem_dir, verbose: true)
    FileUtils.rm_rf("#{gem_dir}/lib/cobhan/output", verbose: true)

    platform_dirs.each do |platform_dir|
      dest_dir = "#{gem_dir}/lib/cobhan/#{platform_dir}"
      FileUtils.mkdir_p(dest_dir, verbose: true)
      FileUtils.cp_r("lib/cobhan/output/#{platform_dir}/.", dest_dir, verbose: true)
    end

    FileUtils.cd(gem_dir, verbose: true) do
      gemspec = Bundler.load_gemspec("cobhan.gemspec")
      gemspec.platform = Gem::Platform.new(platform)
      spec_path = "cobhan.gemspec"
      File.write(spec_path, gemspec.to_ruby)
      sh("gem build -V '#{spec_path}'")

      # puts gemspec.file_name
      # sh("gem install #{gemspec.file_name}")
    end
  end
end

task build_smoke_test: :build do
  gemspec = Bundler.load_gemspec("cobhan.gemspec")
  sh("gem install pkg/#{gemspec.file_name}")
  sh("ruby spec/gem_smoke_test.rb")
end
